version: "3.8"
services:
  php-apache:
    container_name: php-apache-pdl
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8003:80

  db:
    container_name: db-pdl
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin-pdl
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

  composer:
    container_name: composer-pdl
    image: composer:latest
    command: [ "composer", "install" ]
    volumes:
      - ./www:/app
